kismet:
  group1:
    base:
      - dot11.device
      - dot11.device.last_beaconed_ssid_record
    fields:
      ssid: dot11.advertisedssid.ssid
      channel: dot11.advertisedssid.channel
  group2:
    base:
      - dot11.device
    fields:
      bssid: dot11.device.last_bssid
